// flow-typed signature: 14094d0aaf87a5ed5b1cbad2f121bfc1
// flow-typed version: <<STUB>>/babel-plugin-transform-async-generator-functions_v^6.17.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-async-generator-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-async-generator-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-async-generator-functions/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-async-generator-functions/lib/index' {
  declare module.exports: $Exports<'babel-plugin-transform-async-generator-functions/lib'>;
}
declare module 'babel-plugin-transform-async-generator-functions/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-async-generator-functions/lib'>;
}
