// flow-typed signature: 6b854103af1d997ed0c57a7359b36d3c
// flow-typed version: <<STUB>>/deep-assign_v^2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-assign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'deep-assign/index' {
  declare module.exports: $Exports<'deep-assign'>;
}
declare module 'deep-assign/index.js' {
  declare module.exports: $Exports<'deep-assign'>;
}
