// flow-typed signature: 07c1f23601ff6ff49b1160a54aa2329f
// flow-typed version: <<STUB>>/superagent-mocker_v^0.5.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-mocker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-mocker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-mocker/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-mocker/index' {
  declare module.exports: $Exports<'superagent-mocker'>;
}
declare module 'superagent-mocker/index.js' {
  declare module.exports: $Exports<'superagent-mocker'>;
}
declare module 'superagent-mocker/test.js' {
  declare module.exports: $Exports<'superagent-mocker/test'>;
}
